export { default as WhitepaperSection } from "./Whitepaper";
export { default as StepsSection } from "./Steps";
export { default as HeaderSection } from "./Header";
export { default as StatsSection } from "./Stats";
export { default as DescriptionSection } from "./Description";
export { default as NftSection } from "./Nft";
export { default as ContactSection } from "./Contact";
export { default as FooterSection } from "./Footer";
export { default as UniswapSection } from "./Uniswap";
